### ISSUE TITLE
DarkMode Flickering

### ISSUE THREAD

**Issue by viscerae** [viscerae/optimaldnd#2]
When page is in dark mode it seems to cause issues when refreshing or hopping onto another page, the darkmode setting seem to take a while to change so it flickers white for a second, cant seem to make js run faster so it doesnt happen.

**Comment by amanreddy77** [comment]
hey @Viscerae  after careful observation the flickering and slow rendering is because you havent used any library like vite or react if you assign me  this issue i can create a new repo and push changes ?

**Comment by Viscerae** [comment]
I pushed your first changes to the main branch but they didn't work, you were assigned to solve this, hopefully you can lend a hand :) thank you

**Comment by amanreddy77** [comment]
yeah ok 
i will work on this

**Comment by amanreddy77** [comment]
hey @Viscerae  this issue has been solved just check the deployment link in the action pages you won't see any flickering issues and if we run locally then we may notice that this is because rendering issues, these are just minor please reply to me after you check

**Comment by Viscerae** [comment]
The deployment link shows the flickering issues, im pretty sure its due to the page loading before js and css render the stylization of the page, wouldn't it be possible to make them initialize before the page fully loads? this should prevent flickering

**Comment by amanreddy77** [comment]
hey @Viscerae I have solved this issue and made PR's which will fix the issue and enhance the smoother transitions between dark and light modes when navigating through pages and feel free to assign me if any issues arrive in further and just reply me after merging the changes

**Comment by Viscerae** [comment]
Hey, the problem seems to be partially resolved, they do load smoother but not every single time, switching between pages gives less flicker now though.

**Comment by amanreddy77** [comment]
I have made one final PR can you merge it and let me know?

**Comment by Viscerae** [comment]
Merged, dark mode stopped working, im probably going to remove the slider and set it only to dark mode, can you do that? I'll close the issue afterwards.

**Comment by amanreddy77** [comment]
yeak ok i will do it

**Comment by amanreddy77** [comment]
final changes are made just check and let me know please

**Comment by viscerae** [comment]
> final changes are made just check and let me know please

Fixed, thank you 👍🏻 @amanreddy77

**Comment by amanreddy77** [comment]
Just let me know if any issues arise further in the development of the project!
